---
name: Prepare, build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        working-directory: ./build
        run: |
          cmake ..
          cmake --build .

      - name: Run tests
        working-directory: ./build/test
        run: ./cpp_katas_test --output=color

  build-macos:
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        working-directory: ./build
        run: |
          cmake ..
          cmake --build .

      - name: Run tests
        working-directory: ./build/test
        run: ./cpp_katas_test --output=color

  build-windows:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install needed software
        run: |
          choco install ninja

      - name: Build
        working-directory: ./build
        run: |
          cmake -G "Ninja" ..
          cmake --build .

      - name: Run tests
        working-directory: ./build/test
        run: .\cpp_katas_test.exe --output=color
