---
name: Prepare, build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build/test
          ./cpp_katas_test --output=color

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build/test
          ./cpp_katas_test --output=color

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install needed software
        run: |
          choco install ninja

      - name: Build
        run: |
          cd build
          cmake -G "Ninja" ..
          cmake --build .

      - name: Run tests
        run: |
          cd build/test
          .\cpp_katas_test.exe --output=color
